"use client";
import { useEffect, useState } from "react";
import Link from "next/link";
import { useSession } from "next-auth/react";

export default function TwoFactorPage() {
  const { update } = useSession();
  const [enabled, setEnabled] = useState(false); const [qr, setQr] = useState(""); const [secret, setSecret] = useState(""); const [code, setCode] = useState(""); const [recovery, setRecovery] = useState<string[]>([]); const [message, setMessage] = useState("");
  useEffect(() => { fetch("/api/user/two-factor").then((r) => r.json()).then((d) => setEnabled(Boolean(d.enabled))); }, []);
  async function start() { const r = await fetch("/api/user/two-factor", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action: "start" }) }); const d = await r.json(); if (r.ok) { setQr(d.qrCode); setSecret(d.secret); } else setMessage(d.error); }
  async function confirm() { const r = await fetch("/api/user/two-factor", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action: "confirm", code }) }); const d = await r.json(); if (r.ok) { setEnabled(true); setRecovery(d.recoveryCodes); setQr(""); await update({ twoFactorEnabled: true }); } else setMessage(d.error); }
  async function disable() { if (!window.confirm("Disable two-factor authentication?")) return; await fetch("/api/user/two-factor", { method: "DELETE" }); setEnabled(false); await update({ twoFactorEnabled: false }); }
  return <div className="mx-auto max-w-lg space-y-5"><Link href="/settings" className="text-sm font-semibold text-trust">Back to settings</Link><div className="glass-surface rounded-3xl p-6 space-y-4"><h1 className="text-2xl font-extrabold text-primary">Authenticator 2FA</h1><p className="text-sm text-text-secondary">Administrator and moderator access requires 2FA. Scan the QR code with an authenticator app, then enter its six-digit code.</p>{message && <p className="rounded-xl bg-risk-high-bg p-3 text-sm text-risk-high">{message}</p>}{enabled ? <button onClick={disable} className="rounded-xl bg-risk-high px-4 py-3 font-bold text-white">Disable 2FA</button> : !qr ? <button onClick={start} className="rounded-xl bg-primary px-4 py-3 font-bold text-white">Set up authenticator</button> : <div className="space-y-3"><img src={qr} alt="Authenticator QR code" className="mx-auto rounded-xl"/><p className="break-all text-xs text-text-secondary">Manual key: {secret}</p><input value={code} onChange={(e) => setCode(e.target.value.replace(/\D/g, ""))} inputMode="numeric" autoComplete="one-time-code" maxLength={6} placeholder="6-digit code" className="w-full rounded-xl border p-3"/><button onClick={confirm} className="w-full rounded-xl bg-primary p-3 font-bold text-white">Confirm and enable</button></div>}{recovery.length > 0 && <div className="rounded-xl bg-surface-muted p-4"><h2 className="font-bold">Save these one-time recovery codes</h2><p className="mt-1 text-xs text-text-secondary">Each code works once. They cannot be shown again.</p><div className="mt-2 grid grid-cols-2 gap-2 font-mono text-sm">{recovery.map((item) => <span key={item}>{item}</span>)}</div></div>}</div></div>;
}
